fail_fast: false
exclude: ^.*\b(migrations)\b.*$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: pretty-format-json
        args: [
          --autofix,
          --indent 4,
        ]
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [
          --branch, master,
          --branch, main,
        ]

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.2
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]

-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args: [
            --in-place,
            --remove-all-unused-imports,
            --ignore-init-module-imports,
            --remove-unused-variables,
        ]

# -   repo: https://github.com/psf/black
#     rev: 22.3.0
#     hooks:
#     -   id: black
#         language_version: python3.9
#         args: ['-S']


-   repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
    -   id: isort

-  repo: https://github.com/myint/docformatter
   rev: v1.3.1
   hooks:
     - id: docformatter
       args: [
           --in-place,
           --blank,
       ]

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.942
#     hooks:
#     -   id: mypy
#         args: [--ignore-missing-imports]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [
          --config=.flake8,
          --max-line-length=120,
        ]
        exclude: .git|__pycache__
        additional_dependencies:
          - flake8-builtins>=1.5.3
          - flake8-commas>=2.0.0
          - flake8-debugger>=4.0.0
          - flake8-comprehensions>=3.3.1
          - flake8-eradicate>=1.0.0
          - dlint>=0.11.0

-   repo: https://github.com/milin/giticket
    rev: v1.3
    hooks:
      - id: giticket
        args: [
          '--regex=[A-Za-z]+-\d+',
          '--format=[{ticket}] {commit_msg}',
        ]
