FROM python:3.9-alpine

WORKDIR /app

ADD requirements.txt requirements.txt

RUN \
 apk add --no-cache postgresql-libs && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev

RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

EXPOSE 8000

ADD src/ .

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]