version: '3.9'

services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - classroom_db:/var/lib/postgresql/data
    env_file: .env
    container_name: classroom-db
    ports:
      - "5433:5432"
    networks:
      - classroom-network

  back:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./docker/start_app.sh
    volumes:
      - ./:/code/
      - certbot_volume:/etc/letsencrypt/
      - certbot_files:/var/www/certbot/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    container_name: classroom-back
    restart: always
    networks:
      - classroom-network

  huey:
    container_name: classroom-huey
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run huey_consumer.py core.scheduler.start_huey.huey_app -w 4 -k process
    volumes:
      - ./:/code/
    env_file:
      - .env
    depends_on:
      - db
      - back
    networks:
      - classroom-network

  redis:
    image: redis:alpine
    container_name: classroom-redis
    volumes:
      - ./storage/redis:/data
    networks:
      - classroom-network

  back_nginx:
    container_name: back_nginx
    restart: unless-stopped
    image: nginx
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - certbot_files:/var/www/certbot/
        - certbot_volume:/etc/letsencrypt/
    networks:
      - classroom-network

  back_certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_volume:/etc/letsencrypt/
      - certbot_files:/var/www/certbot/
    command: certonly --webroot -w /var/www/certbot --force-renewal --email slavik46111@gmail.com -d api.bezpart.ru --agree-tos
    networks:
      - classroom-network
    depends_on:
      - db
      - back

volumes:
  classroom_db:
  certbot_volume:
  certbot_files:

networks:
  classroom-network:
