"""Add profile_picture_user_id column

Revision ID: 13ed9ba455e6
Revises: bfd263dc402e
Create Date: 2022-07-22 17:54:12.944136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ed9ba455e6'
down_revision = 'bfd263dc402e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('profile_picture_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'users', ['profile_picture_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'attachments', ['profile_picture_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'profile_picture_user_id')
    # ### end Alembic commands ###
