"""added reset password deadline field to user model

Revision ID: 18a45580fcc2
Revises: 9f3bca65c1db
Create Date: 2022-07-09 18:53:30.257343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18a45580fcc2'
down_revision = '9f3bca65c1db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_deadline', sa.DateTime(), nullable=True))
    op.drop_column('users', 'reset_deadline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_reset_deadline')
    # ### end Alembic commands ###
