"""allow delete posts with attachments

Revision ID: 60c401798398
Revises: 18a45580fcc2
Create Date: 2022-07-15 16:46:28.655621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c401798398'
down_revision = '18a45580fcc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attachments_post_id_fkey', 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key('attachments_post_id_fkey', 'attachments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
