"""added reset deadline field to user model

Revision ID: 9f3bca65c1db
Revises: 33d75ac278b0
Create Date: 2022-07-09 18:49:47.153729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3bca65c1db'
down_revision = '33d75ac278b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_deadline')
    # ### end Alembic commands ###
