"""added user avatar field

Revision ID: b74c5ff203e0
Revises: 6df9b833bf68
Create Date: 2022-07-25 18:49:37.311786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74c5ff203e0'
down_revision = '6df9b833bf68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
