"""Add profile_picture_id column

Revision ID: bfd263dc402e
Revises: 6df9b833bf68
Create Date: 2022-07-21 12:46:45.268359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd263dc402e'
down_revision = '6df9b833bf68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_id')
    # ### end Alembic commands ###
