"""password is not nessecary now

Revision ID: 008dacd4ad86
Revises: 7ec92b5bb513
Create Date: 2023-03-07 21:49:37.629837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008dacd4ad86'
down_revision = '7ec92b5bb513'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
