"""allow delete on room

Revision ID: 33f8bbd1dcb2
Revises: 7953f4b763c5
Create Date: 2022-07-15 16:56:43.393393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f8bbd1dcb2'
down_revision = '7953f4b763c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
