"""added attachment profile picture flag

Revision ID: 494cc696290e
Revises: c62255c9c6a3
Create Date: 2022-07-26 21:00:26.969524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494cc696290e'
down_revision = 'c62255c9c6a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('is_profile_picture', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'is_profile_picture')
    # ### end Alembic commands ###
