"""allow delete on multiple models

Revision ID: 7953f4b763c5
Revises: 60c401798398
Create Date: 2022-07-15 16:53:36.682285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7953f4b763c5'
down_revision = '60c401798398'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assignments_post_id_fkey', 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('attachments_assignment_id_fkey', 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('posts_room_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_room_id_fkey', 'posts', 'rooms', ['room_id'], ['id'])
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key('attachments_assignment_id_fkey', 'attachments', 'assignments', ['assignment_id'], ['id'])
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key('assignments_post_id_fkey', 'assignments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
