"""added topics

Revision ID: 7dbf1b532905
Revises: c01843691fa0
Create Date: 2023-03-23 07:53:56.709135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbf1b532905'
down_revision = 'c01843691fa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_phone_number_key', 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_phone_number_key', 'users', ['phone_number'])
    # ### end Alembic commands ###
