"""added topic to rooms

Revision ID: 848bcb068ca7
Revises: 25d51d4bf05c
Create Date: 2023-04-09 09:42:44.910992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848bcb068ca7'
down_revision = '25d51d4bf05c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'topic_id')
    # ### end Alembic commands ###
